import { Volunteer, HeadOfDepartment } from './types';

export const MOCK_VOLUNTEERS: Volunteer[] = [
  {
    id: "mock-1",
    memberId: "TG000001",
    fullName: "Oluwaseun Emmanuel",
    phoneNumber: "08034455667",
    whatsappNumber: "08034455667",
    email: "seun.emmanuel@gmail.com",
    gender: "Male",
    dateOfBirth: "1988-06-15",
    maritalStatus: "Married",
    address: "24, Aladelola Street, Gbagada, Lagos",
    churchDuration: "Over 1 year",
    churchMember: true,
    houseFellowshipStatus: true,
    houseFellowshipName: "Peaceful Centre, Gbagada",
    workersTrainingStatus: "I have completed the programme.",
    completionDate: "2024-11-10",
    firstUnit: "Choir",
    secondUnit: "Media (Photography, Social Media, Livestreaming)",
    flexibleUnit: true,
    skills: ["Vocalist", "Keyboardist", "Event Management"],
    reasonForService: "To glorify God through my singing talent and support the church worship atmosphere.",
    sundayAvailability: true,
    meetingsAvailability: true,
    trainingAvailability: true,
    programmesAvailability: true,
    recommendationType: "Unit Leader",
    recommendationName: "Pastor David Alao",
    commitmentAgreed: true,
    registrationDate: "2026-02-15",
    createdAt: "2026-02-15T09:00:00.000Z",
    updatedAt: "2026-02-15T09:00:00.000Z"
  },
  {
    id: "mock-2",
    memberId: "TG000002",
    fullName: "Chioma Adebayo",
    phoneNumber: "08169988223",
    whatsappNumber: "08169988223",
    email: "chioma.adebayo@outlook.com",
    gender: "Female",
    dateOfBirth: "1994-11-22",
    maritalStatus: "Single",
    address: "Block 4A, Landmark Estate, Lekki, Lagos",
    churchDuration: "6–12 months",
    churchMember: true,
    houseFellowshipStatus: true,
    houseFellowshipName: "Grace House fellowship",
    workersTrainingStatus: "I am currently undergoing the programme.",
    class: "Enrolled in Cohort B",
    firstUnit: "Technical (Sound, Lighting, Projection)",
    secondUnit: "Creative (Drama, Dance, Arts)",
    flexibleUnit: false,
    skills: ["Audio Systems", "Lighting Setup", "Drama Coordinator"],
    reasonForService: "I want to assist with production, sound, and lighting to make services flawless.",
    sundayAvailability: true,
    meetingsAvailability: false,
    trainingAvailability: true,
    programmesAvailability: true,
    recommendationType: "House Fellowship Leader",
    recommendationName: "Deacon Samuel Obi",
    commitmentAgreed: true,
    registrationDate: "2026-03-01",
    createdAt: "2026-03-01T12:30:00.000Z",
    updatedAt: "2026-03-01T12:30:00.000Z"
  },
  {
    id: "mock-3",
    memberId: "TG000003",
    fullName: "Adebayo Johnson",
    phoneNumber: "09023344556",
    whatsappNumber: "09023344556",
    email: "johnson.adebayo@yahoo.com",
    gender: "Male",
    dateOfBirth: "1991-03-10",
    maritalStatus: "Married",
    address: "12, Shiro Street, Fadeyi, Lagos",
    churchDuration: "Over 1 year",
    churchMember: true,
    houseFellowshipStatus: false,
    workersTrainingStatus: "I have completed the programme.",
    completionDate: "2023-05-18",
    firstUnit: "Ushering",
    secondUnit: "Security",
    flexibleUnit: true,
    skills: ["Crowd Management", "Safety", "Hospitality"],
    reasonForService: "I have a heart for hospitality and welcoming guests into God's presence.",
    sundayAvailability: true,
    meetingsAvailability: true,
    trainingAvailability: false,
    programmesAvailability: true,
    recommendationType: "Pastor",
    recommendationName: "Pastor Kunle Martins",
    commitmentAgreed: true,
    registrationDate: "2026-04-10",
    createdAt: "2026-04-10T14:15:00.000Z",
    updatedAt: "2026-04-10T14:15:00.000Z"
  },
  {
    id: "mock-4",
    memberId: "TG000004",
    fullName: "Funmilayo George",
    phoneNumber: "07061122334",
    whatsappNumber: "07061122334",
    email: "funmi.george@gmail.com",
    gender: "Female",
    dateOfBirth: "1997-09-05",
    maritalStatus: "Single",
    address: "8, Pipeline Avenue, Surulere, Lagos",
    churchDuration: "3–6 months",
    churchMember: false,
    houseFellowshipStatus: false,
    workersTrainingStatus: "I have not yet enrolled.",
    enrollNextClass: true,
    firstUnit: "Media (Photography, Social Media, Livestreaming)",
    secondUnit: "Creative (Drama, Dance, Arts)",
    flexibleUnit: true,
    skills: ["Photography", "Graphic Design", "Social Media Management"],
    reasonForService: "I specialize in content creation and want to help the Church expand its digital outreach.",
    sundayAvailability: true,
    meetingsAvailability: true,
    trainingAvailability: true,
    programmesAvailability: true,
    recommendationType: "None",
    commitmentAgreed: true,
    registrationDate: "2026-05-01",
    createdAt: "2026-05-01T10:11:00.000Z",
    updatedAt: "2026-05-01T10:11:00.000Z"
  },
  {
    id: "mock-5",
    memberId: "TG000005",
    fullName: "Chidi Okafor",
    phoneNumber: "08022334455",
    whatsappNumber: "08022334455",
    email: "chidi.okafor@gmail.com",
    gender: "Male",
    dateOfBirth: "1983-04-18",
    maritalStatus: "Married",
    address: "5, Harmony Court, Maryland, Lagos",
    churchDuration: "Over 1 year",
    churchMember: true,
    houseFellowshipStatus: true,
    houseFellowshipName: "Maryland Joy Center",
    workersTrainingStatus: "I have completed the programme.",
    completionDate: "2022-08-30",
    firstUnit: "Security",
    secondUnit: "Logistics/Transport",
    flexibleUnit: false,
    skills: ["First Aid", "Crisis Management", "Driving"],
    reasonForService: "To keep the church clean, secured, and organized for members.",
    sundayAvailability: true,
    meetingsAvailability: true,
    trainingAvailability: true,
    programmesAvailability: false,
    recommendationType: "Unit Leader",
    recommendationName: "Brother Jude Egwu",
    commitmentAgreed: true,
    registrationDate: "2026-05-20",
    createdAt: "2026-05-20T08:44:00.000Z",
    updatedAt: "2026-05-20T08:44:00.000Z"
  },
  {
    id: "mock-6",
    memberId: "TG000006",
    fullName: "Esther Nelson",
    phoneNumber: "08134422558",
    whatsappNumber: "08134422558",
    email: "esther.nelson@hotmail.com",
    gender: "Female",
    dateOfBirth: "1992-12-01",
    maritalStatus: "Single",
    address: "15, Bishop Street, Ikeja, Lagos",
    churchDuration: "Over 1 year",
    churchMember: true,
    houseFellowshipStatus: true,
    houseFellowshipName: "Ikeja Fellowship Unit",
    workersTrainingStatus: "I have completed the programme.",
    completionDate: "2025-01-15",
    firstUnit: "Ushering",
    secondUnit: "Logistics/Transport",
    flexibleUnit: true,
    skills: ["Coordination", "Inventory Management", "French Translator"],
    reasonForService: "To serve in any capacity to assist new visitors and volunteers.",
    sundayAvailability: true,
    meetingsAvailability: true,
    trainingAvailability: true,
    programmesAvailability: true,
    recommendationType: "Church Worker",
    recommendationName: "Sister Blessing Paul",
    commitmentAgreed: true,
    registrationDate: "2026-06-02",
    createdAt: "2026-06-02T16:12:00.000Z",
    updatedAt: "2026-06-02T16:12:00.000Z"
  }
];

export const MOCK_HODS: HeadOfDepartment[] = [
  { id: 'hod-1', fullName: 'Pastor Victor', department: 'Prayer', email: 'prayer.hod@teamglory.com', phoneNumber: '+234 801 111 2222' },
  { id: 'hod-2', fullName: 'Deacon John Ade', department: 'Choir', email: 'choir.hod@teamglory.com', phoneNumber: '+234 802 222 3333' },
  { id: 'hod-3', fullName: 'Sister Sarah Obi', department: 'Hospitality/Protocol', email: 'hospitality.hod@teamglory.com', phoneNumber: '+234 803 333 4444' },
  { id: 'hod-4', fullName: 'Brother David Cole', department: 'Technical (Sound, Lighting, Projection)', email: 'tech.hod@teamglory.com', phoneNumber: '+234 804 444 5555' },
];

